docs_dir: docs_source
site_dir: docs
site_name: Joyanta Debnath | Portfolio
site_description: M.Tech Remote Sensing | Civil Engineering | Water Resources  
site_url: https://joyantadeb.github.io

theme:
  name: material
  palette:
    - scheme: light
      primary: blue
      accent: cyan
  
  font:
    text: Segoe UI
    code: Roboto Mono
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest

extra_css:
  - css/style.css

markdown_extensions:
  - pymdownx.emoji
  - tables

nav:
  - Home: index.md
  - Research:
    - Water Quality: feni_river.md
    - Varuna System: varuna.md
    - Composting Study: composting.md
  - Contact: contact.md